# _config.yml — JavaEvolution site configuration

title: "Java Evolution – Learning, Growing, Mastering"
description: "A GitHub Pages site powered by Jekyll to explore Java in depth."
theme: jekyll-theme-slate

plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-feed

relative_links:
  enabled: true
  collections: true

# Only include files within this directory (no ../)
include:
  - Explaination.md
  - content.md
  - index.md
  - assets/

# If your repo name is part of the GitHub Pages URL,
# set baseurl accordingly. Example:
# baseurl: "/JavaEvolution-Learning-Growing-Mastering"
# If publishing to the root (username.github.io), leave blank or remove.
baseurl: "/JavaEvolution-Learning-Growing-Mastering"

# For proper link handling
markdown: kramdown
