title: Java Evolution – Learning, Growing, Mastering
description: A GitHub Pages site powered by Jekyll to explore Java in depth.
theme: jekyll-theme-slate

plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-feed

relative_links:
  enabled: true
  collections: true

# ✅ Only include files within this directory (no ../)
include:
  - Explaination.md
  - content.md
  - index.md
  - assets/

# ✅ Optional: If your repo name is part of the GitHub Pages URL
# Example: someshdiwan.github.io/JavaEvolution-Learning-Growing-Mastering
# Then set baseurl like this:
baseurl: "/JavaEvolution-Learning-Growing-Mastering"

# For proper link handling
markdown: kramdown
